apiVersion: v1
kind: Secret
metadata:
  name: postgresql
type: Opaque
data:
  postgresql-password: cGFzc3dvcmQ=
  password: cGFzc3dvcmQ=

# bitnami/postgres expects 'postgresql-password' key for password