apiVersion: v1
kind: ConfigMap
metadata:
  name: flyway-migration-{{.Chart.Name}}-configmap
  labels:
    {{- include "keymap.labels" . | nindent 4 }}
data:
  {{- (.Files.Glob "flyway/sql/**.*").AsConfig | nindent 2 }}