{{- if and .Values.secrets.imagePullSecret.username .Values.secrets.imagePullSecret.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Chart.Name}}-imagepullsecret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecretTemplate" . }}
{{- end }}

---

  {{- if .Values.db.password }}
    {{- if not .Values.localDatastoreSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{.Chart.Name}}-datastore
type: Opaque
data:
  password: {{ .Values.db.password | b64enc }}
    {{- end }}
  {{- end }}