services:
  rabbitmq:
    image: rabbitmq:management
    hostname: 'MyRabbit'
    container_name: 'MyRabbit-1'
    ports:
      - "15672:15672"
      - "15673:5672"
    volumes:
      - /tmp/data/MyRabbit-1/data:/var/lib/rabbitmq
      - /tmp/data/MyRabbit-1/log:/var/log/rabbitmq
    networks:
      - wxrabbitnet
networks:
  wxrabbitnet:
    name: wxrabbitnet
    driver: bridge

########################################################
# Rabbit uses an internal Erlang-bases MNESIA database #
# for persistence. Information is stored on the volume #
# defined for data and therefore survives container    #
# restarts. No Shovels supported on this image.        #
#            	                                      #
# Default admin login is guest/guest.                  #
########################################################     
