apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keymapdb
  name: keymapdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keymapdb
  template:
    metadata:
      labels:
        app: keymapdb
    spec:
      containers:
      - image: mongo
        name: keymapdb
        env:
          - name: KEYMAP_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: keymap-configmap
                key: KEYMAP_DB_NAME
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: keymap-secret
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: keymap-secret
                key: mongo-root-password
        ports:
        - containerPort: 27017
        volumeMounts:
          - name: keymapdb-volume-mount
            mountPath: /data/db
      volumes:
        - name: keymapdb-volume-mount
          persistentVolumeClaim:
            claimName: postgres-pvc
      restartPolicy: Always