apiVersion: v1
kind: Service
metadata:
  name: keym-app
  labels:
    service: keym-app
spec:
  type: NodePort
  selector:
    app: keym-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500

---
apiVersion: v1
kind: Service
metadata:
  name: keymapdb
  labels:
    service: keymapdb
spec:
  type: ClusterIP
  selector:
    app: keymapdb
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
