version: '3'
services:
  keymapper:
    image: postgres:13.3
    container_name: keymap-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keymap