version: "3.8"
services:
  keym-app:
    hostname: ${KEYMAP_APP_HOST}
    container_name: ${KEYMAP_APP_HOST}
    build: ./pyflask
    image: keymapp:0.1-SNAPSHOT
    command: python -u main.py
    environment:
      - KEYMAP_DB_HOST
      - KEYMAP_DB_PORT
      - KEYMAP_DB_USERNAME
      - KEYMAP_DB_PASSWORD_FILE=/run/secrets/postgres_db_password
      - KEYMAP_DB_NAME
      - IDP_JWKS_HOST
      - IDP_JWKS_PORT
      - IDP_JWKS_PATH
      - IDP_JWT_AUDIENCE
      - KEYMAP_DISABLE_JWT_VALIDATION
    secrets:
      - postgres_db_password
    ports:
      - ${KEYMAP_APP_PORT}:5000
    volumes:
      - ./src:/app
    depends-on:
      - keymap-pgdb
    networks:
      - postgresnet

  keymap-pgdb:
    image: postgres:13.3
    hostname: ${KEYMAP_DB_HOST}
    container_name: ${KEYMAP_DB_HOST}
    volumes:
      - ./tmp/data:/var/lib/postgresql/data
      - ./postgres/scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - postgresnet
    ports:
      - "5970:5432"
    environment:
      POSTGRES_USER: ${KEYMAP_DB_USERNAME}
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_db_password
      POSTGRES_DB: ${KEYMAP_DB_NAME}
    secrets:
      - postgres_db_password

secrets:
  postgres_db_password:
    file: ./secrets/postgres_db_password

networks:
  postgresnet:
    name: postgresnet
    driver: bridge

