profiles: development
fullnameOverride: "keymap-service"
localDatastoreSecret: false

db:
  host: postgresql
  database: keymap
  username: postgres

image:
  repository: "<<Insert repository name here>>"
  version: latest
  pullPolicy: Always

ingress:
  enabled: false

environment:
  DISABLE_JWT_VALIDATION: false
  IDP_JWKS_HOST:
  IDP_JWKS_PORT: 443
  IDP_JWKS_PATH: /auth/realms/MY_REALM/protocol/openid-connect/certs
  IDP_JWT_AUDIENCE: account

