version: "3.8"
services:
  keym-app:
    hostname: ${KEYMAP_APP_HOST}
    container_name: ${KEYMAP_APP_HOST}
    build: ./pyflask
    image: keymapp:0.1-SNAPSHOT
    command: python -u main.py
    environment:
      - KEYMAP_DB_HOST
      - KEYMAP_DB_PORT
      - KEYMAP_DB_USERNAME_FILE=/run/secrets/mongo_admin_user
      - KEYMAP_DB_PASSWORD_FILE=/run/secrets/mongo_admin_password
#      - KEYMAP_DB_USERNAME
#      - KEYMAP_DB_PASSWORD
      - KEYMAP_DB_NAME
      - IDP_JWKS_HOST
      - IDP_JWKS_PORT
      - IDP_JWKS_PATH
      - IDP_JWT_AUDIENCE
      - KEYMAP_DISABLE_JWT_VALIDATION
    secrets:
      - mongo_admin_password
      - mongo_admin_user
    ports:
      - ${KEYMAP_APP_PORT}:5000
    volumes:
      - ./src:/app
    links:
      - keymap-db
    networks:
      - mongonet
  keymap-db:
    hostname: ${KEYMAP_DB_HOST}
    container_name: ${KEYMAP_DB_HOST}
    image : mongo
    environment:
      - MONGO_INITDB_DATABASE=${KEYMAP_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongo_admin_user
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongo_admin_password
#      - MONGO_INITDB_ROOT_USERNAME=${KEYMAP_DB_USERNAME}
#      - MONGO_INITDB_ROOT_PASSWORD=${KEYMAP_DB_PASSWORD}
    secrets:
      - mongo_admin_password
      - mongo_admin_user
    restart: unless-stopped
    networks:
      - mongonet
    ports:
      - 27017:27017

secrets:
  mongo_admin_user:
    file: ./secrets/mongo_admin_user
  mongo_admin_password:
    file: ./secrets/mongo_admin_password
networks:
  mongonet:
    name: mongonet
    driver: bridge

