apiVersion: apps/v1
kind: Deployment
metadata:
  name: keym-app
  labels:
    app: keym-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keym-app
  template:
    metadata:
      labels:
        app: keym-app
    spec:
      containers:
        - name: keym-app
          image: keym-app:0.1-SNAPSHOT
          env:
            - name: FLASK_ENV
              value: "development"
            - name: KEYMAP_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: keymap-configmap
                  key: KEYMAP_DB_HOST
            - name: KEYMAP_DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: keymap-configmap
                  key: KEYMAP_DB_PORT
            - name: KEYMAP_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: keymap-configmap
                  key: KEYMAP_DB_NAME
            - name: KEYMAP_DISABLE_JWT_VALIDATION
              valueFrom:
                configMapKeyRef:
                  name: keymap-configmap
                  key: KEYMAP_DISABLE_JWT_VALIDATION
            - name: IDP_JWKS_HOST
              valueFrom:
                configMapKeyRef:
                  name: keymap-configmap
                  key: IDP_JWKS_HOST
            - name: IDP_JWKS_PORT
              valueFrom:
                configMapKeyRef:
                  name: keymap-configmap
                  key: idp_jwks_port
            - name: IDP_JWKS_PATH
              valueFrom:
                configMapKeyRef:
                  name: keymap-configmap
                  key: IDP_JWKS_PATH
            - name: IDP_JWT_AUDIENCE
              valueFrom:
                configMapKeyRef:
                  name: keymap-configmap
                  key: IDP_JWKS_AUDIENCE
            - name: KEYMAP_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keymap-secret
                  key: mongo-root-username
            - name: KEYMAP_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keymap-secret
                  key: mongo-root-username
          ports:
          - containerPort: 5000