version: "3.8"
services:
  keymap-app:
    hostname: ${KEYMAP_APP_HOST}
    build: .
    environment:
      - KEYMAP_DB_HOST
      - KEYMAP_DB_PORT
      - KEYMAP_DB_USERNAME
      - KEYMAP_DB_PASSWORD_FILE=/run/secrets/keymap-datastore-password
      - KEYMAP_DB_NAME
      - IDP_JWKS_HOST
      - IDP_JWKS_PORT
      - IDP_JWKS_PATH
      - IDP_JWT_AUDIENCE
      - DISABLE_JWT_VALIDATION
      - ENFORCE_JWT_AUTHENTICATION
    secrets:
      - keymap-datastore-password
    volumes:
      - ./src/python/app:/app
    ports:
      - ${KEYMAP_APP_PORT}:5000
    networks:
      - postgresnet
    depends_on:
      - flyway
      - keymap-db

  keymap-db:
    image: postgres:13.3
    hostname: ${KEYMAP_DB_HOST}
    volumes:
      - ./tmp/data:/var/lib/postgresql/data
    networks:
      - postgresnet
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${KEYMAP_DB_USERNAME}
      POSTGRES_PASSWORD_FILE: /run/secrets/keymap-datastore-password
      POSTGRES_DB: ${KEYMAP_DB_NAME}
    secrets:
      - keymap-datastore-password

  flyway:
    image: flyway/flyway:8.1
    command: -url=jdbc:postgresql://${KEYMAP_DB_HOST}:${KEYMAP_DB_PORT}/${KEYMAP_DB_NAME} -user=${KEYMAP_DB_USERNAME} -connectRetries=60 migrate
    volumes:
      - ./helm/keymap-service/flyway/sql:/flyway/sql
    environment:
      FLYWAY_PASSWORD: ${KEYMAP_DB_PASSWORD}
    networks:
      - postgresnet
    depends_on:
      - keymap-db

secrets:
  keymap-datastore-password:
    file: ./secrets/keymap-datastore-password

networks:
  postgresnet:
    name: postgresnet
    driver: bridge

